name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: latex_example.tex
          working_directory: latex-example
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: latex-example/latex_example.pdf
